//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Mgnt_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventDBEntities : DbContext
    {
        public EventDBEntities()
            : base("name=EventDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Booking_Events> Booking_Events { get; set; }
        public DbSet<BookingFlower> BookingFlowers { get; set; }
        public DbSet<DecorationEquipment> DecorationEquipments { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<FoodItem> FoodItems { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<tbl_admin> tbl_admin { get; set; }
        public DbSet<User_Feedback> User_Feedback { get; set; }
    }
}
