//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Mgnt_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Booking_Events = new HashSet<Booking_Events>();
        }
    
        public int Package_ID { get; set; }
        public string Package_Name { get; set; }
    
        public virtual ICollection<Booking_Events> Booking_Events { get; set; }
    }
}
